language: minimal
jobs:
  include:
    env: CATEGORY_TO_TEST=regression
    env: CATEGORY_TO_TEST=regressionEXT
    env: CATEGORY_TO_TEST=multivariate
    env: CATEGORY_TO_TEST=clustering
    env: CATEGORY_TO_TEST=utilities
    env: CATEGORY_TO_TEST=graphics
dist: xenial
install:
    - travis_wait 60
    - wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
script: matlab -batch "run runAllMyTestsFS.m"       

 