language: minimal
dist: xenial
install:
    - travis_wait 30
    - wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
    strategy:
      matrix:
        regression:
          categoryName: 'regression'
        graphics:
          categoryName: 'graphics'
        multivariate:
          categoryName: 'multivariate'
        clustering:
          categoryName: 'clustering'
        utilities:
          categoryName: 'utilities'
    pool:
      vmImage: 'Ubuntu 16.04'
      timeoutInMinutes: 0 
    variables:
      CATEGORY_TO_TEST: $(categoryName)
    steps:
script: matlab -batch "run runAllMyTestsFS.m"       