jobs:
- job: Test
  strategy:
      matrix:
        regression:
          categoryName: 'regression'
        regressionTS:
          categoryName: 'regressionTS'
        regressionLTSts:
          categoryName: 'regressionLTSts'
        regressionEXT:
          categoryName: 'regressionEXT'
        graphics:
          categoryName: 'graphics'
        multivariate:
          categoryName: 'multivariate'
        multivariate-clustering:
          categoryName: 'multivariate-clustering'
        regression-clustering:
          categoryName: 'regression-clustering'
        mixsim:
          categoryName: 'mixsim'
        utilities:
          categoryName: 'utilities'
        tclustMULT:
          categoryName: 'tclustMULT'
        tclustMULTgpcm:
          categoryName: 'tclustMULTgpcm'
  pool:
      vmImage: 'ubuntu-latest'
  variables:
      CATEGORY_TO_TEST: $(categoryName)
  steps:
     - task: InstallMATLAB@1
      inputs:
        release: R2023a
        products: |
          MATLAB
          Optimization_Toolbox
          Statistics_and_Machine_Learning_Toolbox
     - task: RunMATLABCommand@0 
      inputs:
        command: "run runAllMyTestsFS.m" 
     - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml'  
     - script: |
        bash <(curl -s https://codecov.io/bash)
      displayName: 'Upload to codecov.io'
     - task: PublishPipelineArtifact@1
      condition: always()
      inputs:
        path: $(System.DefaultWorkingDirectory)/tests-$(categoryName)
        artifact: Test-$(categoryName)
     - task: PublishCodeCoverageResults@1
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '**/coverage-*.xml'  