jobs:
 "regression":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regression"  
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
         

 "regressionEXT":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regressionEXT"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
       - run:  
           command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
           no_output_timeout: 60m 

workflows:
  version: 2
  build:
    jobs:
      - "regression"
      - "regressionEXT"



