version: 2
jobs:
 "regression":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regression"  
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-regression/test-regression-report/
       
 "regressionTS":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regressionTS"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-regressionTS/test-regressionTS-report/

 "regressionLTSts":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regressionLTSts"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-regressionLTSts/test-regressionLTSts-report/

 "regressionEXT":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regressionEXT"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-regressionEXT/test-regressionEXT-report/
        

 "graphics":
   build:
   environment: 
     - CATEGORY_TO_TEST: "graphics"  
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-graphics/test-graphics-report/
        

 "multivariate":
   build:
   environment: 
     - CATEGORY_TO_TEST: "multivariate"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-multivariate/test-multivariate-report/

 "multivariate-clustering":
   build:
   environment: 
     - CATEGORY_TO_TEST: "multivariate-clustering"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-multivariate-clustering/test-multivariate-clustering-report/

 "regression-clustering":
   build:
   environment: 
     - CATEGORY_TO_TEST: "regression-clustering"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-regression-clustering/test-regression-clustering-report/


 "mixsim":
   build:
   environment: 
     - CATEGORY_TO_TEST: "mixsim"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-mixsim/test-mixsim-report/


 "utilities":
   build:
   environment: 
     - CATEGORY_TO_TEST: "utilities"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-utilities/test-utilities-report/

 "tclustMULT":
   build:
   environment: 
     - CATEGORY_TO_TEST: "tclustMULT"
   machine:
      image: ubuntu-1604:201903-01
   steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run:  
          command: matlab -batch "run runAllMyTestsFS.m"                                                                                    -
          no_output_timeout: 60m 
      - store_test_results:
          path: ~/project/tests-tclustMULT/test-tclustMULT-report/

workflows:
  version: 2
  build:
    jobs:
      - "regression"
      - "regressionTS"
      - "regressionLTSts"
      - "regressionEXT"
      - "graphics"
      - "multivariate"
      - "multivariate-clustering"
      - "regression-clustering"
      - "mixsim"
      - "utilities"
      - "tclustMULT"



