version: 2.1
orbs:
  matlab: mathworks/matlab@0.1
jobs:
  build:
    parameters:
      categorytotest:
        description: category to test
        type: string    
    machine:
      image: ubuntu-1604:201903-01
    environment: 
     - CATEGORY_TO_TEST: << parameter.categorytotest >>
    steps:
      - checkout
      - matlab/install     
      - matlab/run-command:              
          command: "run runAllMyTestsFS.m"               
      - store_test_results:
        path: ~/project/tests-<< parameter.categorytotest >>/test-<< parameter.categorytotest >>-report/
        

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
               categorytotest: ["regression", "regressionTS", "regressionLTSts", "regressionEXT", "graphics", "multivariate", "multivariate-clustering", "regression-clustering", "mixsim", "utilities", "tclustMULT"]



