# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the MATLAB-orb
  matlab: mathworks/matlab@0.1
jobs:
# Name the job "testing"
  testing:
  # define some parameters to be used inside the job
     parameters:
       p:
         default: 1
         type: integer    
       categorytotest:
         default: "regression"
         type: string    
     parallelism: << parameters.categorytotest >>    
     environment:
       CATEGORY_TO_TEST: << parameters.categorytotest >>  # setup a parametric environment variable to be used by MATLAB testing script "runAllMyTestsFS.m"
     machine:
         image: ubuntu-1604:201903-01
     steps:
        - checkout
        - matlab/install                       # previously `wget ...`
        - matlab/run-command:                  # previously `matlab -batch ...`   
            command: "run runAllMyTestsFS.m"    # run the testing script: the environment variable can be retieved using 'var=getenv('CATEGORY_TO_TEST');'
        - store_test_results:
            path: ~/project/tests-<<parameter.categorytotest>>/test-<<parameter.categorytotest>>-report/
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  fsdatoolbox:
    # Run the "testing" job defined earlier in its own container
    jobs:
      - testing:
      # Define a matrix of parameter values to be passed iteratively to the "testing" job
          matrix:
             parameters:
                  categorytotest: ["regression", "regressionTS", "regressionLTSts", "regressionEXT", "graphics", "multivariate", "multivariate-clustering", "regression-clustering", "mixsim", "utilities", "tclustMULT"]

