# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the MATLAB-orb
  matlab: mathworks/matlab@0.1
jobs:
# Name the job "testing"
  testing:
  # define q: parameter; used inside the jobs: to segment the tests to overcome the 50 minutes limit.
     parameters:
      q:
         default: "regression"
         type: string      
     environment:
       CATEGORY_TO_TEST: << parameters.q >>  # setup a parametric environment variable to be used by MATLAB testing script "runAllMyTestsFS.m"
     machine:
         image: ubuntu-1604:201903-01
     steps:
        - checkout
        - matlab/install                        # previously `wget ...`
        - matlab/run-command:                   # previously `matlab -batch ...`   
            command:  
              "run runAllMyTestsFS.m"    # run the testing script: the environment variable can be retrieved using 'var=getenv('CATEGORY_TO_TEST');'
        - store_test_results:
            path: ~/project/tests-<< parameters.q >>/test-<< parameters.q >>-report/

# Orchestrate or schedule a set of jobs
workflows:
  # Name of the workflow 
  fsdatoolbox:
    # Run the "testing" job defined earlier in its own container
    jobs:
      - testing:
      # Define a matrix of parameter values to be passed iteratively to the "testing" job
          matrix:
             parameters:
                  q: ["regression", "regressionTS", "regressionLTSts", "regressionEXT", "graphics", "multivariate", "multivariate-clustering", "regression-clustering", "mixsim", "utilities", "tclustMULT"]

